# Language and its version
language: python
python:
  - "3.9"

# Needed services, in this case Docker
services:
  - docker

# Execute this line before executing any script, we need Docker!
before_script:
  - pip install docker-compose

# Scripts that Travis will run on each Pull Request
script:
  # Run PyLint tests inside "/app/tests"
  - docker-compose run --no-deps app pylint tests
  # Run Flake8 tests inside "/app/tests"
  - docker-compose run --no-deps app flake8 tests
  # Run PyTests tests inside "/app/tests"
  - docker-compose run app pytest tests